version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - sh -c 'cd ui && 
      curl -fsSL https://nodejs.org/dist/v22.0.0/node-v22.0.0-linux-x64.tar.gz -o node.tar.gz && 
      tar xf node.tar.gz && 
      export PATH=$PWD/node-v22.0.0-linux-x64/bin:$PATH && 
      npm install -g npm && 
      npm install && 
      npm run build && 
      cd .. && 
      rm -rf goseg/web && 
      mkdir -p goseg/web && 
      mv ui/build/* goseg/web/'

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64
binary: groundseg_amd64
dir: ./goseg
main: .

builds:
  - main: ./goseg

ldflags:
  - "-X main.Version=${VERSION}"
  - "-X main.Commit=${COMMIT}"
  - "-X main.CommitDate=${COMMIT_DATE}"
  - "-X main.TreeState=${TREE_STATE}"
