version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: "{{.Arch}}"
binary: "groundseg_{{.Arch}}"
builds:
  - main: ./goseg

ldflags:
  - "-X main.Version={{.Env.VERSION}}"
  - "-X main.Commit={{.Env.COMMIT}}"
  - "-X main.CommitDate={{.Env.COMMIT_DATE}}"
  - "-X main.TreeState={{.Env.TREE_STATE}}"