version: 1

before:
  hooks:
    - sh -c 'cd ui && 
      curl -fsSL https://nodejs.org/dist/v22.0.0/node-v22.0.0-linux-x64.tar.gz -o node.tar.gz && 
      tar xf node.tar.gz && 
      export PATH=$PWD/node-v22.0.0-linux-x64/bin:$PATH && 
      npm install -g npm && 
      npm install && 
      npm run build && 
      cd .. && 
      rm -rf goseg/web && 
      mkdir -p goseg/web && 
      mv ui/build/* goseg/web/'

builds:
  - id: groundseg
    dir: ./goseg
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
    main: .
    binary: groundseg_amd64
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -X main.Version={{ .Env.VERSION }}
      - -X main.Commit={{ .Env.COMMIT }}
      - -X main.CommitDate={{ .Env.COMMIT_DATE }}
      - -X main.TreeState={{ .Env.TREE_STATE }}
