version: 1
goos: linux
goarch: amd64
binary: groundseg_amd64
dir: ./goseg
main: .
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
flags:
  - -trimpath
  - -tags=netgo
ldflags:
  - "-X main.Version={{ .Env.VERSION }}"
  - "-X main.Commit={{ .Env.COMMIT }}"
  - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
  - "-X main.TreeState={{ .Env.TREE_STATE }}"
before:
  hooks:
    - sh -c 'cd ui && 
      curl -fsSL https://nodejs.org/dist/v22.0.0/node-v22.0.0-linux-x64.tar.gz -o node.tar.gz && 
      tar xf node.tar.gz && 
      export PATH=$PWD/node-v22.0.0-linux-x64/bin:$PATH && 
      npm install -g npm && 
      npm install && 
      npm run build && 
      cd .. && 
      rm -rf goseg/web && 
      mkdir -p goseg/web && 
      mv ui/build/* goseg/web/'
