---
version: "3.9"
services:
  api:
    build: ./api
    ports: 
      - 27016:27016
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - groundseg-api:/settings
      - /var/lib/docker/volumes:/var/lib/docker/volumes
volumes:
  groundseg-api:
