---
version: "3.9"
services:
  api:
    build: ./api
    container_name: groundseg_api
    privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports: 
      - 27016:27016
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - settings:/settings

  webui:
    build: ./ui
    container_name: groundseg_webui
    privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports: 
      - 80:3000

volumes:
  settings:
